
package ku.vc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VolumeUnit", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/convertVolume.asmx?WSDL")
public class VolumeUnit
    extends Service
{

    private final static URL VOLUMEUNIT_WSDL_LOCATION;
    private final static WebServiceException VOLUMEUNIT_EXCEPTION;
    private final static QName VOLUMEUNIT_QNAME = new QName("http://www.webserviceX.NET/", "VolumeUnit");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/convertVolume.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VOLUMEUNIT_WSDL_LOCATION = url;
        VOLUMEUNIT_EXCEPTION = e;
    }

    public VolumeUnit() {
        super(__getWsdlLocation(), VOLUMEUNIT_QNAME);
    }

    public VolumeUnit(WebServiceFeature... features) {
        super(__getWsdlLocation(), VOLUMEUNIT_QNAME, features);
    }

    public VolumeUnit(URL wsdlLocation) {
        super(wsdlLocation, VOLUMEUNIT_QNAME);
    }

    public VolumeUnit(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VOLUMEUNIT_QNAME, features);
    }

    public VolumeUnit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VolumeUnit(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VolumeUnitSoap
     */
    @WebEndpoint(name = "VolumeUnitSoap")
    public VolumeUnitSoap getVolumeUnitSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "VolumeUnitSoap"), VolumeUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VolumeUnitSoap
     */
    @WebEndpoint(name = "VolumeUnitSoap")
    public VolumeUnitSoap getVolumeUnitSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "VolumeUnitSoap"), VolumeUnitSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VOLUMEUNIT_EXCEPTION!= null) {
            throw VOLUMEUNIT_EXCEPTION;
        }
        return VOLUMEUNIT_WSDL_LOCATION;
    }

}
