
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VolumeUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VolumeUnitSoap {


    /**
     * 
     * @param volumeValue
     * @param toVolumeUnit
     * @param fromVolumeUnit
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeVolumeUnit", action = "http://www.webserviceX.NET/ChangeVolumeUnit")
    @WebResult(name = "ChangeVolumeUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeVolumeUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeVolumeUnit")
    @ResponseWrapper(localName = "ChangeVolumeUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeVolumeUnitResponse")
    public double changeVolumeUnit(
        @WebParam(name = "VolumeValue", targetNamespace = "http://www.webserviceX.NET/")
        double volumeValue,
        @WebParam(name = "fromVolumeUnit", targetNamespace = "http://www.webserviceX.NET/")
        Volumes fromVolumeUnit,
        @WebParam(name = "toVolumeUnit", targetNamespace = "http://www.webserviceX.NET/")
        Volumes toVolumeUnit);

}
